spring:
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
    datasource:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:testdb
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mysql://${DB_URL:localhost:33306/ozik}?allowMultiQueries=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
#        username: sa
#        password:

    jpa:
#        database-platform:
        show-sql: true
        hibernate:
            ddl-auth: create-drop
            ddl-auto: create
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379


springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
        tags-sorter: alpha # 태그 정렬 기준
        path: /swagger-ui.html # html 문서 접속 경로
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
        doc-expansion: none # tag, operation 펼치는 방식
    paths-to-match:
        - /**

side-pot:
    access-key: zsdioufgasdoifyuq3jklrhzdkjlvhuiotyvo7q8yrojoisedhsakjlvnzcx5fds23dafa8j
    refresh-key: zxcvlkjdsfiopufas8301d3cnsddcn3h9cnu0qvasdfsdagdfgdfshbbvccsdzl2