spring:
    # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
    h2:
    console:
    enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
    path: /h2-console  # H2 Console의 Path
    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
    datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)


springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
        tags-sorter: alpha # 태그 정렬 기준
        path: /swagger-ui.html # html 문서 접속 경로
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
        doc-expansion: none # tag, operation 펼치는 방식
    paths-to-match:
        - /**